/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class DarkEmpireActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.darkempire || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  
  /**
   * Prepare Character type specific data
   */
  _prepareCharacterData(actorData) {
    if (actorData.type !== 'character') return;

    // Make modifications to data here. For example:
    const systemData = actorData.system;

    // Loop through ability scores, and add their modifiers to our sheet output.
    for (let [key, ability] of Object.entries(systemData.abilities)) {
      // Calculate the modifier using morrow project rules.
      ability.mod = Math.floor((ability.value *2));
    }
    let choices = { 
      "8": "Petite",
      "9": "Small",
      "10": "Medium",
      "11": "Large",
      "12": "Huge"}
    let value = "8";

     // Ensure that attributes and structure_points exist before accessing
  if (systemData.attributes && systemData.attributes.structure_points) {
    systemData.attributes.structure_points.value = 
     ( (systemData.abilities.str.value + systemData.abilities.con.value) / 2) * systemData.attributes.mass.value;
    } else {
  console.warn("structure_points or its parent objects are undefined");
}

// Mass value interpretation
  if (systemData.attributes && systemData.attributes.mass) {
    const massValue = systemData.attributes.mass.value;
    systemData.attributes.mass.label = 
      systemData.attributes.mass.options[massValue] || "Unknown";
  }
  }

}
